export const ADD_TO_BASKET_ACTION = 'ADD_TO_BASKET_ACTION';
export const REMOVE_FROM_BASKET_ACTION = 'REMOVE_FROM_BASKET_ACTION';
export const GET_DATA = 'GET_DATA';
export const CART_IS_OPEN = 'CART_IS_OPEN';